// Generated by CoffeeScript 1.7.1

/*
The background class renders the part of the game behind the paddle, ball, and blocks.
 */
var Background,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Background = (function(_super) {
  __extends(Background, _super);

  function Background(game) {
    this.game = game;
    Background.__super__.constructor.call(this);
  }


  /*
  Draw the background.
   */

  Background.prototype.draw = function(context) {
    context.fillStyle = this.game.colours.getColour('gameBackground');
    return context.fillRect(this.game.playArea.x, this.game.playArea.y, this.game.playArea.width, this.game.playArea.height);
  };

  return Background;

})(Entity);
