// Generated by CoffeeScript 1.7.1

/*
The background class renders the part of the game behind the paddle, ball, and blocks.
 */
var Background,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Background = (function(_super) {
  __extends(Background, _super);

  function Background() {
    return Background.__super__.constructor.apply(this, arguments);
  }

  Background.prototype.construct = function() {
    return Background.__super__.construct.call(this);
  };

  Background.prototype.draw = function(context) {
    context.fillStyle = game.colours.getColour('gameBackground');
    return context.fillRect(0, 0, game.width, game.height);
  };

  return Background;

})(Entity);
