// Generated by CoffeeScript 1.7.1

/*
The Ball class is an Entity.
 */
var Ball,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Ball = (function(_super) {
  __extends(Ball, _super);


  /*
  Construct a ball
   */

  function Ball(radius) {
    this.radius = radius != null ? radius : 4;
    Ball.__super__.constructor.call(this);
    this.height = this.radius * 2;
    this.reset();
  }

  Ball.prototype.reset = function() {
    var maxVector, minVector, randVector;
    this.x = game.width / 2;
    this.y = game.height / 2;
    this.velocity = 5;
    this.vector = 90;
    minVector = -25;
    maxVector = 25;
    randVector = Math.floor(Math.random() * (maxVector - minVector + 1) + minVector);
    return this.vector += randVector;
  };


  /*
  Update the position of the ball, taking into account the entities around
  the ball.
   */

  Ball.prototype.update = function(steps) {
    Ball.__super__.update.call(this, steps);
    if (this.y >= game.height - this.radius) {
      this.y = game.height - this.radius;
      return this.bounce(270);
    } else if (this.y <= this.radius) {
      this.y = this.radius;
      return this.bounce(90);
    } else if (this.x <= this.radius) {
      this.x = this.radius;
      return this.bounce(360);
    } else if (this.x >= game.width - this.radius) {
      this.x = game.width - this.radius;
      return this.bounce(180);
    }
  };


  /*
  Draw the ball on the given drawing surface.
   */

  Ball.prototype.draw = function(context) {
    context.beginPath();
    context.arc(this.x, this.y, this.radius, 0, 2 * Math.PI, false);
    context.fillStyle = game.colours.getColour("ballBackground");
    context.fill();
    context.lineWidth = 1;
    context.strokeStyle = game.colours.getColour("ballStroke");
    return context.stroke();
  };


  /*
  Bounce the ball on the given surface. The surface is specified by it's perpendicular angle.
   */

  Ball.prototype.bounce = function(normal) {
    var m, o;
    o = this.vector - 180 - normal;
    m = normal - o;
    if (m <= 0) {
      m += 360;
    } else if (m > 360) {
      m -= 360;
    }
    return this.vector = m;
  };

  return Ball;

})(Entity);
