// Generated by CoffeeScript 1.7.1
var BlockMap,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BlockMap = (function(_super) {
  __extends(BlockMap, _super);


  /*
  Construct a BlockMap with the given blocks.
   */

  function BlockMap(blocks) {
    this.blocks = blocks != null ? blocks : [];
    BlockMap.__super__.constructor.call(this);
  }


  /*
  Update all the blocks in this BlockMap.
   */

  BlockMap.prototype.update = function(steps) {
    var block, _i, _len, _ref, _results;
    BlockMap.__super__.update.call(this, steps);
    _ref = this.blocks;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      block = _ref[_i];
      _results.push(block.update(steps));
    }
    return _results;
  };


  /*
  Draw all the blocks in this BlockMap.
   */

  BlockMap.prototype.draw = function(context) {
    var block, _i, _len, _ref, _results;
    BlockMap.__super__.draw.call(this, context);
    _ref = this.blocks;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      block = _ref[_i];
      _results.push(block.draw(context));
    }
    return _results;
  };

  BlockMap.prototype.blocksRemaining = function() {
    var block, remaining, _i, _len, _ref;
    remaining = 0;
    _ref = this.blocks;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      block = _ref[_i];
      if (!block.removed) {
        remaining++;
      }
    }
    return remaining;
  };

  BlockMap.prototype.reset = function() {
    var block, _i, _len, _ref, _results;
    _ref = this.blocks;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      block = _ref[_i];
      _results.push(block.reset());
    }
    return _results;
  };


  /*
  Build the standard grid of blocks.
   */

  BlockMap.getBlockMap = function(game) {
    var blockHeight, blockMap, blockNum, blockWidth, leftGutter, numBlocksPerRow, numRows, padding, rowNum, topGutter, x, y, _i, _j;
    blockMap = new BlockMap([]);
    leftGutter = 25;
    topGutter = 30;
    padding = 0;
    blockHeight = 20;
    numBlocksPerRow = 13;
    blockWidth = (game.playArea.width - leftGutter * 2 - padding * (numBlocksPerRow - 1)) / numBlocksPerRow;
    numRows = 9;
    for (rowNum = _i = 0; 0 <= numRows ? _i < numRows : _i > numRows; rowNum = 0 <= numRows ? ++_i : --_i) {
      for (blockNum = _j = 0; 0 <= numBlocksPerRow ? _j < numBlocksPerRow : _j > numBlocksPerRow; blockNum = 0 <= numBlocksPerRow ? ++_j : --_j) {
        x = game.playArea.x + leftGutter + (blockWidth * blockNum) + padding * blockNum;
        y = game.playArea.y + topGutter + (blockHeight * rowNum) + padding * rowNum;
        blockMap.blocks.push(new Block(game, x, y, blockWidth, blockHeight, rowNum + blockNum % 5));
      }
    }
    return blockMap;
  };

  return BlockMap;

})(Entity);
