// Generated by CoffeeScript 1.7.1
var ColourScheme;

ColourScheme = (function() {
  function ColourScheme(colours) {
    this.colours = colours;
  }

  ColourScheme.prototype.setColour = function(identifier, colour) {
    return this.colours[identifier] = colour;
  };

  ColourScheme.prototype.getColour = function(identifier) {
    return this.colours[identifier];
  };

  ColourScheme.getMooduinoColourScheme = function() {
    return new ColourScheme({
      gameBackground: '#DFF',
      ballBackground: '#0F0',
      ballStroke: '#030',
      paddleBackground: 'yellow',
      paddleStroke: 'black'
    });
  };

  return ColourScheme;

})();
