// Generated by CoffeeScript 1.7.1
var ColourScheme;

ColourScheme = (function() {

  /*
  Construct a ColourScheme with the given colours.
   */
  function ColourScheme(colours) {
    this.colours = colours;
  }


  /*
  Get the named colour.
   */

  ColourScheme.prototype.getColour = function(identifier) {
    return this.colours[identifier];
  };


  /*
  Get the standard colour scheme.
   */

  ColourScheme.getMooduinoColourScheme = function() {
    return new ColourScheme({
      gameBackground: "#DFF",
      ballBackground: "#0F0",
      ballStroke: "#030",
      paddleBackground: "yellow",
      paddleStroke: "black",
      scoreBoardBackground: "#333",
      scoreBoardForeground: "#CCC",
      messageBoxBackground: "Black",
      messageBoxForeground: "White"
    });
  };

  return ColourScheme;

})();
