// Generated by CoffeeScript 1.7.1
var canvas, game;

window.requestAnimationFrame = window.requestAnimationFrame || window.mozRequestAnimationFrame || window.webkitRequestAnimationFrame || window.msRequestAnimationFrame;

canvas = $('#breakout')[0];

game = new Game(canvas);

game.colours = ColourScheme.getMooduinoColourScheme();

game.addEntity(new Background(game), "background");

game.addEntity(new ScoreBoard(game), "scoreBoard");

game.addEntity(BlockMap.getBlockMap(game), "blockMap");

game.addEntity(new Ball(game), "ball");

game.addEntity(new Paddle(game), "paddle");

game.start();

canvas.focus();
