// Generated by CoffeeScript 1.7.1
var ScoreBoard,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ScoreBoard = (function(_super) {
  __extends(ScoreBoard, _super);

  function ScoreBoard(game, height) {
    this.game = game;
    this.height = height != null ? height : 25;
    ScoreBoard.__super__.constructor.call(this);
  }

  ScoreBoard.prototype.update = function(steps) {
    return ScoreBoard.__super__.update.call(this, steps);
  };

  ScoreBoard.prototype.draw = function(context) {
    context.fillStyle = this.game.colours.getColour('scoreBoardBackground');
    context.fillRect(0, 0, game.width, this.height);
    context.fillStyle = this.game.colours.getColour('scoreBoardForeground');
    context.font = '12px monospace';
    context.fillText("Score: " + this.game.score, 20, 16);
    return context.fillText("Lives: " + this.game.lives, this.game.width / 2 + 20, 16);
  };

  return ScoreBoard;

})(Entity);
